# These are environment variable names used by the test framework
PYINT_CAPTURE = "PYINT_TEST_CAPTURE"
PYINT_LOG_COMMANDS = "PYINT_TEST_LOG_COMMANDS"
PYINT_LOG_OUTPUT = "PYINT_TEST_LOG_OUTPUT"
PYINT_JOB_ID = "PYINT_TEST_JOB_ID"
PYINT_KNOWN_ISSUES = "PYINT_TEST_KNOWN_ISSUES"

